repos:
- repo: https://github.com/willthames/ansible-lint.git
  rev: v3.4.23
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: trailing-whitespace
